apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-contador
spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-contador

  template:
    metadata:
      labels:
        app: api-contador

    spec:
      containers:
        - name: api-contador
          image: api-contador:latest
          imagePullPolicy: Never
          env:
            - name: DB_NOME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
            - name: DB_USUARIO
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: DB_SENHA
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: JWT_SECRET
            
          ports:
            - containerPort: 8081
          
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"