apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: c3VhX2Jhc2VfNjRfYXF1aQ==
  POSTGRES_USER: c3VhX2Jhc2VfNjRfYXF1aQ==
  POSTGRES_PASSWORD: c3VhX2Jhc2VfNjRfYXF1aQ==