spring.application.name=api-contador

spring.datasource.url=jdbc:postgresql://postgres-service:5432/${DB_NOME}
spring.datasource.username=${DB_USUARIO}
spring.datasource.password=${DB_SENHA}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
server.port: 8081